spring:
  application:
    name: jwt-auth-app
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/UserInfo
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: "Your mail"
    password: "Your mail's app password"

    protocol: smtp
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true