spring:
  application:
    name: jwt-auth-app
  datasource:
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/auth_db
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: "MAIL"
    password: "PASS"
    protocol: smtp
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true